name: Build & Release
on: 
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Visual Studio Build Environment
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Build Executable and DLL
        run: nmake release

      - name: Create Release
        run: gh release create ${{ github.event.inputs.version }} ./release/lightwm.exe ./release/lightwm_dll.dll -n "Version ${{ github.event.inputs.version }}"
